import './globals.css'
import { Inter } from 'next/font/google'
import { Navbar } from 'react-bootstrap'
import NavbarDark from './components/Navbar'
import Footer from './components/Footer'
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarDark></NavbarDark>
        {children}
        <Footer></Footer>
        </body>
    </html>
  )
}
